CREATE TABLE Branch(
branchNo VARCHAR(45) NOT NULL UNIQUE PRIMARY KEY, 
street VARCHAR(255) NOT NULL, 
city VARCHAR(45) NOT NULL,
postcode INT);

CREATE TABLE Staff(
staffNo VARCHAR(45) NOT NULL UNIQUE  PRIMARY KEY,
fname VARCHAR(65) NOT NULL,
lname VARCHAR(65) NOT NULL,
position VARCHAR(65) NOT NULL,
sex ENUM('Male', 'Female') DEFAULT('Male'),
DOB VARCHAR(65) NOT NULL,
salary INT NOT NULL,
branchNo VARCHAR(45) NOT NULL,
FOREIGN KEY (branchNo) REFERENCES Branch(branchNo)
ON DELETE CASCADE
ON UPDATE CASCADE);

CREATE TABLE PropertyForRent(
propertyNo VARCHAR(45) NOT NULL UNIQUE PRIMARY KEY,
street VARCHAR(255) NOT NULL, 
city VARCHAR(45) NOT NULL,
postcode INT,
type VARCHAR(45) NOT NULL,
rooms VARCHAR(45) NOT NULL,
rent INT NOT NULL,
ownerNo VARCHAR(45) NOT NULL,
FOREIGN KEY (ownerNo) REFERENCES PrivateOwner(ownerNo)
ON DELETE CASCADE
ON UPDATE CASCADE);

CREATE TABLE Client(
clientNo VARCHAR(45) NOT NULL UNIQUE  PRIMARY KEY,
fname VARCHAR(65) NOT NULL,
lname VARCHAR(65) NOT NULL,
telNo INT,
prefType VARCHAR(45),
maxRent INT,
eMail VARCHAR(45) NOT NULL UNIQUE);

CREATE TABLE PrivateOwner(
ownerNo VARCHAR(45) NOT NULL UNIQUE  PRIMARY KEY,
fname VARCHAR(65) NOT NULL,
lname VARCHAR(65) NOT NULL,
address VARCHAR(65) NOT NULL,
telNo INT,
eMail VARCHAR(45) NOT NULL UNIQUE,
password VARCHAR(45) NOT NULL);

CREATE TABLE Viewing(
viewDate VARCHAR(45),
comment VARCHAR(255),
clientNo VARCHAR(45) NOT NULL,
FOREIGN KEY (clientNo) REFERENCES Client(clientNo)
ON DELETE CASCADE
ON UPDATE CASCADE,
propertyNo VARCHAR(45) NOT NULL,
FOREIGN KEY (propertyNo) REFERENCES PropertyForRent(propertyNo)
ON DELETE CASCADE
ON UPDATE CASCADE);

CREATE TABLE Registration(
clientNo VARCHAR(45) NOT NULL,
FOREIGN KEY (clientNo) REFERENCES Client(clientNo)
ON DELETE CASCADE
ON UPDATE CASCADE,
branchNo VARCHAR(45) NOT NULL,
FOREIGN KEY (branchNo) REFERENCES Branch(branchNo)
ON DELETE CASCADE
ON UPDATE CASCADE,
staffNo VARCHAR(45) NOT NULL,
FOREIGN KEY (staffNo) REFERENCES Staff(staffNo)
ON DELETE CASCADE
ON UPDATE CASCADE,
dateJoined VARCHAR(45));